export const POSITION_ATTRIB_LOCATION = 0;
export const NORMAL_ATTRIB_LOCATION = 1;
export const FALLBACK_COLOR_ATTRIB_LOCATION = 2;
export const TEXTURE_LOADED_ATTRIB_LOCATION = 3;
export const TEXCOORD_ATTRIB_LOCATION = 4;
export const TEXINDEX_ATTRIB_LOCATION = 5;